project1/home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # ex: /home/
    path("", views.index, name="index"),
    path("hakkimizda/", views.hakkimizda, name="hakkimizda"),
    path("referances/", views.referances, name="referances"),
    path("iletisim/", views.iletisim, name="iletisim"),
    path("urunler/", views.urunler, name="urunler"),
    path("urunler/<int:id>", views.urun_detay, name="urun_detay"),
    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.product_search_auto, name='product_search_auto'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout_view'),
    path('sss/', views.sss, name='sss'),
    # ex: /home/5/
    #path("<int:question_id>/", views.detail, name="detail"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project1/project1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]

project1/home/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.forms import ModelForm, TextInput , Textarea
from product.models import Product
from django.utils.html import mark_safe

# Create your models here.

class Setting(models.Model):
    STATUS= (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=100)
    keyword = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    adress = models.CharField(blank = True ,max_length=150)
    phone = models.CharField(blank = True ,max_length=15)
    fax = models.CharField(blank = True ,max_length=150)
    email = models.CharField(blank = True ,max_length=50)
    smtpserver = models.CharField(blank = True ,max_length=20)
    smtpemail = models.CharField(blank = True ,max_length=50)
    smtppassword = models.CharField(blank = True ,max_length=10)
    smtpport = models.CharField(blank = True , max_length=5)
    icon = models.ImageField(upload_to='images/', blank = True)
    facebook = models.CharField(blank = True ,max_length=50)
    instagram = models.CharField(blank = True ,max_length=50)
    twitter = models.CharField(blank = True ,max_length=50)
    aboutus = RichTextUploadingField(blank = True )
    contact = RichTextUploadingField(blank = True )
    referances = RichTextUploadingField(blank = True )
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
    
class ContactFormMessage(models.Model):
    STATUS= (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=255)
    subject = models.CharField(max_length=255)
    message = models.CharField(max_length=50)
    status = models.CharField(max_length=10, choices=STATUS,default="New") 
    ip = models.CharField(blank = True ,max_length=15)
    note = models.CharField(blank = True ,max_length=150)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ["name","email","subject","message"]
        wigdets = {
            "name": TextInput(attrs={'class':'input','placeholder':'Name & Surname'}),
            "subject": TextInput(attrs={'class':'input','placeholder':'Subject'}),
            "email": TextInput(attrs={'class':'input','placeholder':'Email Address'}),
            "message": Textarea(attrs={'class':'input','placeholder':'Your Message','rows':'5'}),
        }

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def image_tag(self):
        if self.image:
            return mark_safe('<img src="{}" width="50" height="50" />'.format(self.image.url))
        else:
            return "No Image"

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ["phone", "address", "city", "country", "image"]
        
class FAQ(models.Model):
    STATUS= (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    question = models.CharField(max_length=100)
    answer = models.CharField(max_length=255)
    status = models.CharField(max_length=10,choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.question

project1/product/models.py
from audioop import reverse
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.forms import ModelForm, TextInput , Textarea
from django.contrib.auth.models import User
from django.utils.html import mark_safe

# Create your models here.
class Category(models.Model):
    STATUS= (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=100)
    keyword = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)    
    slug = models.SlugField(null=False, unique=True)
    parent = models.ForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    
    
    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return '-'.join(full_path[::-1])
    
    def get_absolute_url(self):
        return reverse("category_detial", kwargs={"slug": self.slug})
    
    
class Product(models.Model):
    STATUS= (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    category = models.ForeignKey(Category,on_delete=models.CASCADE) # Category tablosuyla ilişki kurulması
    title = models.CharField(max_length=150)
    keyword = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    price = models.FloatField()
    amount = models.IntegerField()
    slug = models.SlugField(unique=True)
    detail = RichTextUploadingField()
    status = models.CharField(max_length=10, choices=STATUS)    
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("product_detial", kwargs={"slug": self.slug})
    
    def image_tag(self):
        if self.image:
            return mark_safe('<img src="{}" width="50" height="50" />'.format(self.image.url))
        else:
            return "No Image"

    

    
class Comment(models.Model):
    STATUS= (
        ('New', 'Yeni'),
        ('True', 'Göster'),
        ('False', 'Gösterme'),
    )
    product = models.ForeignKey(Product,on_delete=models.CASCADE)# Product tablosuyla ilişki kurulması
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    subject = models.CharField(max_length=150,blank=True)
    comment = models.TextField(max_length=255)
    rate = models.IntegerField(blank=True,null=True)
    status = models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True,max_length=20)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    
    def __str__(self): 
        return self.subject
    
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields =['subject','comment','rate']


    

class Images(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    images = models.ImageField(blank=True, upload_to='images/')
    
    
    def __str__(self):
        return self.title

project1/home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SearchForm(forms.Form):
    query = forms.CharField(label="Search", max_length=100)
    
    
class SignUpForm(UserCreationForm):
    username = forms.CharField(label='Kullanıcı Adı', max_length=30)
    email = forms.EmailField(label='Email')
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
        

project1/home/views.py
import json
from django.shortcuts import render,redirect,HttpResponse , HttpResponseRedirect
from order.models import ShopCard
from .models import Setting,ContactFormu,ContactFormMessage , UserProfile ,FAQ
from product.models import Product,Category,Images,Comment
from django.contrib import messages
from product.views import addcomment
from .forms import SearchForm, SignUpForm
from django.contrib.auth import authenticate, login as django_login, logout
from django.utils.crypto import get_random_string

# Create your views here.

def index(request):
    setting = Setting.objects.get()
     # ... Outfit kategorisinin ID'sini veya adını bulun
    men_outfit_category = Category.objects.get(title="Men Outfit")
    women_outfit_category = Category.objects.get(title="Women Outfit")
    kid_outfit_category = Category.objects.get(title="Kid Outfit")

    
    # ... Outfit kategorisine ait ürünleri çekin
    slider_man = Product.objects.filter(category=men_outfit_category)[:4]
    slider_women = Product.objects.filter(category=women_outfit_category)[:4]
    slider_kid = Product.objects.filter(category=kid_outfit_category)[:4]
    current_user = request.user
    request.session['cart_items'] = ShopCard.objects.filter(user_id=current_user.id).count() #Show Count of Items in Cart
    
    #veri çekmek için 

    
    context = {"setting":setting,
               "slider_man":slider_man,
               "slider_women":slider_women,
               "slider_kid":slider_kid,
               }
    return render(request, "home/index.html", context)


def hakkimizda(request):
    setting = Setting.objects.get()
    context = {"setting":setting}
    return render(request, "home/hakkimizda.html",context)

def referances(request):
    setting = Setting.objects.get()
    context = {"setting":setting}
    return render(request, "home/referances.html",context)

def iletisim(request):
    if request.method == 'POST':
        form = ContactFormu(request.POST)
        if form.is_valid():
            data = ContactFormMessage() #Form ile bağlantı kurma
            data.name = form.cleaned_data["name"] #formdan bilgi alma
            data.email = form.cleaned_data["email"]
            data.subject = form.cleaned_data["subject"]
            data.message = form.cleaned_data["message"]
            data.ip = request.META.get("REMOTE_ADDR")
            data.save() #Datayı veritabanına kaydet
            messages.success = (request,"Mesajınız Başarıyla Gönderilmiştir.")
            return redirect ('iletisim')
        
    setting = Setting.objects.get()
    form = ContactFormu()
    context = {"setting":setting, "form":form}
    return render (request, 'home/iletisim.html',context)

def urunler(request):
    setting = Setting.objects.get()
    urunler = Product.objects.all()
    context = {"setting":setting,
               "urunler":urunler}
    
    return render (request, "home/urunler.html",context)

def urun_detay(request,id):
    urunler = Product.objects.get(pk=id)
    resimler = Images.objects.filter(product_id=id)
    comments = Comment.objects.filter(product_id=id,status='True')
    context = {"urunler":urunler,
               "resimler":resimler,
               "comments":comments,}
    return render(request, "home/urun_detay.html",context)
    
def product_search(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            category = Category.objects.all()
            setting = Setting.objects.all()
            query = form.cleaned_data['query']
            products = Product.objects.filter(title__icontains=query)
            
            context = {'products':products,
                        'category':category,
                        'setting':setting,
                        }
            return render(request, 'home/product_search.html',context) 
    return HttpResponseRedirect('/')


def product_search_auto(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        q = request.GET.get('term', '')
        products = Product.objects.filter(title__icontains=q)
        results = [product.title for product in products]
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

def login(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            django_login(request,user)
            return HttpResponseRedirect('/')
        else:
            messages.warning(request,"Login Hatası! Kullanıcı adı veya şifre yanlış.")
            return redirect ('login')
            # Return an 'invalid login' error message.
    return render(request, 'home/login.html')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

from django.contrib.auth import login as django_login

# Your other imports and views...

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            django_login(request, user)  # Use django_login instead of login
            current_user = request.user
            data= UserProfile()
            data.user_id =current_user.id
            data.image = "images/users/user.png"
            data.save(
            messages.success(request , "Sitemize Hoş Geldiniz")
            )
        else:
            form.errors
            return redirect("signup")
        
        return HttpResponseRedirect("/")
    form = SignUpForm()
    context = {'form': form}
    return render(request, 'home/signup.html', context)


def sss(request):
    sss = FAQ.objects.all()
    context = {"sss":sss,}
    return render(request, 'home/faq.html',context)

project1/home/templates/home/banner.html
{% load static %}


  <!-- ***** Ana Banner Alanı Başlangıcı ***** -->
  <div class="main-banner" id="top">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="left-content">
                    <div class="thumb">
                        <div class="inner-content">
                            <h4>Biz Hexashop'uz</h4>
                            <span>SINCE 1974</span>
                            <div class="main-border-button">
                                <a href="{% url 'urunler' %}">Şimdi Satın Al!</a>
                            </div>
                        </div>
                        <img src="{% static 'home/images/left-banner-image.jpg' %}" alt="">
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="right-content">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="right-first-image">
                                <div class="thumb">
                                    <div class="inner-content">
                                        <h4>Kadınlar</h4>
                                        <span>Kadınlar İçin En İyi Kıyafetler</span>
                                    </div>
                                    <div class="hover-content">
                                        <div class="inner">
                                            <h4>Kadınlar</h4>
                                            <p>Lorem ipsum dolor sit amet, conservisii ctetur adipiscing elit incid.</p>
                                            <div class="main-border-button">
                                                <a href="#women">Daha Fazlasını Keşfet</a>
                                            </div>
                                        </div>
                                    </div>
                                    <img src="{% static 'home/images/baner-right-image-01.jpg' %}">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="right-first-image">
                                <div class="thumb">
                                    <div class="inner-content">
                                        <h4>Erkekler</h4>
                                        <span>Erkekler İçin En İyi Kıyafetler</span>
                                    </div>
                                    <div class="hover-content">
                                        <div class="inner">
                                            <h4>Erkekler</h4>
                                            <p>Lorem ipsum dolor sit amet, conservisii ctetur adipiscing elit incid.</p>
                                            <div class="main-border-button">
                                                <a href="#men">Daha Fazlasını Keşfet</a>
                                            </div>
                                        </div>
                                    </div>
                                    <img src="{% static 'home/images/baner-right-image-02.jpg' %}">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="right-first-image">
                                <div class="thumb">
                                    <div class="inner-content">
                                        <h4>Çocuklar</h4>
                                        <span>Çocuklar İçin En İyi Kıyafetler</span>
                                    </div>
                                    <div class="hover-content">
                                        <div class="inner">
                                            <h4>Çocuklar</h4>
                                            <p>Lorem ipsum dolor sit amet, conservisii ctetur adipiscing elit incid.</p>
                                            <div class="main-border-button">
                                                <a href="#kids">Daha Fazlasını Keşfet</a>
                                            </div>
                                        </div>
                                    </div>
                                    <img src="{% static 'home/images/baner-right-image-03.jpg' %}">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="right-first-image">
                                <div class="thumb">
                                    <div class="inner-content">
                                        <h4>Aksesuarlar</h4>
                                        <span>En İyi Trend Aksesuarlar</span>
                                    </div>
                                    <div class="hover-content">
                                        <div class="inner">
                                            <h4>Aksesuarlar</h4>
                                            <p>Lorem ipsum dolor sit amet, conservisii ctetur adipiscing elit incid.</p>
                                            <div class="main-border-button">
                                                <a href="#">Daha Fazlasını Keşfet</a>
                                            </div>
                                        </div>
                                    </div>
                                    <img src="{% static 'home/images/baner-right-image-04.jpg' %}">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ***** Ana Banner Alanı Sonu ***** -->

project1/home/templates/home/urun_detay.html
{% extends 'home/homebase.html' %}
{% load static %}




{% block title %} {{ urunler.title }}{% endblock title%}




{% block header %} {% include 'home/header.html' %} {% endblock %}

{% block content %}

    

     <!-- ***** Main Banner Area Start ***** -->
     <div class="page-heading" id="top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="inner-content">
                        <h2>Ürün Detay Sayfası</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Main Banner Area End ***** -->


    <!-- ***** Product Area Starts ***** -->
    <section class="section" id="product">
        <div class="container">
            <div class="row">
                
                <div class="col-lg-8">
                <div class="left-images">

                    <img src="{{urunler.image.url}}" alt="" >
                    
                </div>
            </div>
            <div class="col-lg-4">
                <div class="right-content">
                    <h4>{{urunler.title}}</h4>
                    <span class="price">{{urunler.price}}₺</span>
                    <span>{{urunler.amount}} adet kaldı.</span>
                    <div class="quote">
                        <i class="fa fa-quote-left"></i><p>{{urunler.description}}</p>
                    </div>
                    
                    <form action="/product/addtocard/{{urunler.id}}" method="post">
                        {% csrf_token %}
                        <div class="quantity-content">
                            <div class="left-content">
                                <h6>Adet</h6>
                            </div>
                            
                        
                            
                        <div class="right-content">
                            <div class="quantity buttons_added">
                                <input type="button" value="-" class="minus"><input type="number" step="1" min="1" max="{{urunler.amount}}" name="quantity" value="1" title="Qty" class="input-text qty text" size="4" pattern="" inputmode=""><input type="button" value="+" class="plus">
                            </div>
                        </div>
                    </div>
                    <div class="total" >
                        <h4>{{urunler.price}}₺</h4>
                        <div class="main-border-button"><a href="/order/addtocard/{{urunler.id}}">Sepete Ekle</a></div>
                    </div>
                    </form>
                    {% for resim in resimler %}
                    <div class="card" style="width: 10rem; margin-top: 150px; margin-bottom: 150px; margin-left:30px;">
                        <img src="{{ resim.images.url }}" class="card-img-top enlarge-image" alt="...">
                    </div>
                    {% endfor %}
                </div>
            </div>
                

                <style>
                    .enlarge-image {
                        transition: transform 0.2s; /* Add a smooth transition effect */
                    }
                
                    .enlarge-image:hover {
                        transform: scale(1.8); /* Enlarge the image to 120% when hovered */
                        cursor: pointer;
                         /* Change the cursor to indicate interactivity */
                    }
                </style>
                


            </div>
            </div>
        </div>
    </section>
    <!-- ***** Product Area Ends ***** -->

    <!-- ***** Comment Area Start ***** -->

    <link rel="stylesheet" href="{% static 'home/css/comment.css' %}" />

    <div class="container">
        <div id="reviews" class="review-section">
            
            

                <div class="col-md-12">
                    <div class="d-flex align-items-center justify-content-between mb-4 col-md-12">
                        <h4>Düşüncelerinizi Belirtiniz</h4>
                        {%if messages %}
                            {%for message in messages %}
                                <div class="alert alert-{{message.tags}}" role="alert">
                                    {{message}}
                                </div>
                            {%endfor%}
                        {%endif%}
                    </div>
                    <form action="/product/addcomment/{{urunler.id}}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="input" type="text" name="subject" id="id_subject" placeholder="Başlık">
            
                    </div>
            
                    <div class="form-group">
                        <textarea class="input" name="comment" id="id_comment" placeholder="Yorumunuz"></textarea>
                    </div>
            
                    <div class="form-group">
                        <strong>Your Rating:</strong>
                        <div class="stars">
                            <input type="radio" id="star1" name="rate" value="1"><label for="star1"></label>
                            <input type="radio" id="star2" name="rate" value="2"><label for="star2"></label>
                            <input type="radio" id="star3" name="rate" value="3"><label for="star3"></label>
                            <input type="radio" id="star4" name="rate" value="4"><label for="star4"></label>
                            <input type="radio" id="star5" name="rate" value="5"><label for="star5"></label>
                        </div>
                    </div>
                    
            
            
                    {% if user.id  is not None%}
            
                    <button class="button-50" style="margin-top:20px; display: flex;justify-content: center; text-align: center;">Gönder</button>
                    {%else%}
                    Yorum Eklemek için Kayıt Olunuz!
                    {%endif%}
                </form>
            </div>
            </div>
        </div>

    
        
        <div class="container">
        {% for rs in comments %}
        <div class="review-list">
            <ul>
                <li>
                    <div class="d-flex">
                        <div class="left">
                            <span>
                                <img src="https://bootdey.com/img/Content/avatar/avatar1.png" class="profile-pict-img img-fluid" alt="" />
                            </span>
                        </div>
                        <div class="right">
                            <h4>
                                {{rs.user.username}}
                                <span class="gig-rating text-body-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1792 1792" width="15" height="15">
                                        <path
                                        fill="currentColor"
                                            d="M1728 647q0 22-26 48l-363 354 86 500q1 7 1 20 0 21-10.5 35.5t-30.5 14.5q-19 0-40-12l-449-236-449 236q-22 12-40 12-21 0-31.5-14.5t-10.5-35.5q0-6 2-20l86-500-364-354q-25-27-25-48 0-37 56-46l502-73 225-455q19-41 49-41t49 41l225 455 502 73q56 9 56 46z"
                                        ></path>
                                    </svg>
                                    {{rs.rate}}
                                </span>
                            </h4>
                            <div class="review-description">
                                <strong>{{rs.subject}}</strong>
                            </div>
                            <div class="review-description">
                                <p>
                                    {{rs.comment}}
                                </p>
                            </div>
                            <span class="publish py-3 d-inline-block w-100">{{rs.create_at}}</span>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
        {% endfor %}
    </div>
<!-- HTML !-->



    <!-- ***** Comment Area End ***** -->

    
    <!-- Add this script block at the end of your HTML template, just before the closing </body> tag -->

<script>
    $(document).ready(function() {
        $('.minus').click(function() {
            var quantityInput = $(this).parent().find('input[name="quantity"]');
            var currentQuantity = parseInt(quantityInput.val(), 10);
            
            if (currentQuantity > 1) {
                quantityInput.val(currentQuantity - 1);
            }
        });

        $('.plus').click(function() {
            var quantityInput = $(this).parent().find('input[name="quantity"]');
            var currentQuantity = parseInt(quantityInput.val(), 10);
            var maxQuantity = parseInt(quantityInput.attr('max'), 10);
            
            if (currentQuantity < maxQuantity) {
                quantityInput.val(currentQuantity + 1);
            }
        });
    });
</script>

{% endblock %}

{% block footer %}{% include 'home/footer.html' %}{% endblock %}